server:
  port: 80

spring:
  application:
    name: cloud-order-service   #当前微服务模块名
  zipkin:
    base-url: http://localhost:9411 #此时注意base_url的对齐方式，要不启动会报错
    sleuth:
      sampler:
        #采样率值介于0~1之间，1表示全部采集，一般设置为0，在并发量高的情况下，一般不会设置为1
        probability: 1
eureka:
  client:
    register-with-eureka: true #入驻eureka server
    fetchRegistry: true #true 代表自己就是客户端 需要提供服务
    service-url:
       defaultZone: http://localhost:7001/eureka  #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/