server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_route2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
          predicates:
             - Path=/payment/lb/**   #断言,路径相匹配的进行路由
           # - Host=**.mr.com
           # - Header=X-Request-Id,\d+
           # - Cookie=username,zzyy
           # - After=2020-08-07T15:07:09.933+08:00[Asia/Shanghai]
           # - Query=username,\d+ #要有参数username,值是正整数


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

